config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'chases/top' => 'chases#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] # ユーザーマイページへのルーティング
  #ここまで

  resources :chases  do
    resources :comments, only: [:create]
  end
  
  
  resources :relationships, only: [:create, :destroy]
  root 'chases#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chase.rb
class Chase < ApplicationRecord
    belongs_to :user 
     has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :chase
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        has_many :chases, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
        validates :name, presence: true #追記
        validates :profile, length: { maximum: 200 } #追記
         has_many :comments, dependent: :destroy
         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user
         
         def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end
      

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
    
end

app/controllers/chases_controller.rb
class ChasesController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create]
  def top

  end

  def index
    @chases = Chase.all
  
  if params[:search] == nil
    @chases= Chase.all
  elsif params[:search] == ''
    @chases= Chase.all
  else
    #部分検索
    @chases = Chase.where("body LIKE ? ",'%' + params[:search] + '%')
  end
  end


  def new
        @chase = Chase.new
      end
    
      def create
        chase= Chase.new(chase_params)
        chase.user_id = current_user.id
        if chase.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end

      end
      def show
        @chase = Chase.find(params[:id])
        @comments = @chase.comments
        @comment = Comment.new
      end
    
      def edit
        @chase = Chase.find(params[:id])
      end

      def update
        chase = Chase.find(params[:id])
        if chase.update(chase_params)
          redirect_to :action => "show", :id => chase.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        chase = Chase.find(params[:id])
        chase.destroy
        redirect_to action: :index
      end
      
      private
      def chase_params
        params.require(:chase).permit(:body, :ace, :king, :queen, :jack, :ten, :nine, :eight, :seven, :six)
      end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      chase = Chase.find(params[:chase_id])
      comment = chase.comments.build(comment_params) #buildを使い、contentとchase_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :set_user
    
    def create
        following = current_user.follow(@user)
        if following.save
         flash[:success] = 'ユーザーをフォローしました'
          redirect_to @user
        else
          flash.now[:alert] = 'ユーザーのフォローに失敗しました'
          redirect_to @user
        end
      end
    
      def destroy
        following = current_user.unfollow(@user)
        if following.destroy
          flash[:success] = 'ユーザーのフォローを解除しました'
          redirect_to @user
        else
          flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
          redirect_to @user
        end
      end
    
      private
      def set_user
        @user = User.find(params[:follow_id])
      end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
      
      def following
        @user  = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end
  
    def followers
      @user  = User.find(params[:id])
      @users = @user.followers
      render 'show_follower'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chases_helper.rb
module ChasesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
     end
end

app/views/chases/edit.html.erb
<%= form_for @chase do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
     <% end %>

app/views/chases/helper.erb
module ChaseaHelpter

    def find_youtube_url(youtube_url)
      if youtube_url[0..16] == "https://youtu.be/"
        return youtube_url[17..27]
        # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
      else
        return youtube_url[32..42]
        # "https://www.youtube.com/watch?v=WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
      end
    end
  end
  

app/views/chases/index.html.erb
<h1>Geekpoker</h1>
<h3>Poker一覧</h3>

<%= link_to "新規投稿へ",new_chase_path, class:"h2" %>

<div class="chases-container">
  <% @chases.each do |t| %>
    <div class="chase">
      <% if t.user %>
        <%= t.user.email %>
        <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
      <% else %>
        <p>ユーザー情報がありません</p>
      <% end %>
      
      <% if user_signed_in? %>
        <%= link_to "マイページへ", user_path(current_user.id) %>
      <% end %>
      
      <h3>投稿を検索</h3>
      <%= form_tag({controller: "chases", action: "index"}, method: :get) do %>
        <%= text_field_tag :search %>
        <%= submit_tag '検索する' %>
      <% end %>
      
      <%= t.body %>
      <%= t.ace %>
      <%= t.king %>
      <%= t.queen %>
      <%= t.jack %>
      <%= t.ten %>
      <%= t.nine %>
      <%= t.eight %>
      <%= t.seven %>
      <%= t.six %>



      <%= link_to "詳細へ", chase_path(t.id) %>
      <%= link_to "編集する", edit_chase_path(t.id) %>
      <%= button_to "削除する", chase_path(t.id), method: :delete %>
    </div>




    <div>
   <p1>質問</p1>
   <p>ここから</p>
</div>
<div class="box"> 
</div>

<header class="header-nav">
<nav><a href=".first-block">Home</a></nav>
<nav><a href=".second-block">About me</a></nav>
<nav><a href=".third-block">Recent Activity</a></nav>
</header>

  <% end %>
</div>

app/views/chases/new.html.erb
<h1>(Geekpoker)</h1>
<h3>新規poker</h3>
<%= form_for @chase do |f| %>




  <div class="field">
    <%= f.label :ace %>
    <%= f.select :ace, 
    ["カード1"], 
    include_blank: "選択して下さい" %>
  </div>

  <div class="field">
  <%= f.label :king %>
  <%= f.select :king, 
  ["カード2"], 
  include_blank: "選択して下さい" %>
</div>

  <div class="field">
    <%= f.label :項目名  %>
    <%= f.number_field :queen, :size => 10 %>
  </div>

  <div class="field">
  <%= f.label :項目名  %>
  <%= f.number_field :jack, :size => 10 %>
</div>

<div class="field">
<%= f.label :項目名  %>
<%= f.number_field :ten, :size => 10 %>
</div>

<div class="field">
<%= f.label :項目名  %>
<%= f.number_field :nine, :size => 10 %>
</div>

<div class="field">
<%= f.label :項目名  %>
<%= f.number_field :eight, :size => 10 %>
</div>

<div class="field">
<%= f.label :項目名  %>
<%= f.number_field :seven, :size => 10 %>
</div>

<div class="field">
<%= f.label :項目名  %>
<%= f.number_field :six, :size => 10 %>
</div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :size => "30x2" %>
  </div>




  <%= f.submit "送信する" %>
<% end %>

<%= link_to "ホームに戻る", chases_path %>

app/views/chases/show.html.erb
<h1>Geekpoker</h1>
<h3>Chase詳細</h3>
<div class="chase">
  <p><%= @chase. body%></p>
  <p><%= @chase.created_at %></p>
</div>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>



  <% if user_signed_in? %>
    <%= form_with(model: [@chase, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
      <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "一覧に戻る", chases_path %>
<%= link_to "編集する", edit_chase_path(@chase.id) %>

app/views/chases/top.html.erb
<div class="poker">
   <div class="porker_1">
      <h1>pokerとは</h1>
      <p>ポーカーは、トランプを使用したカードゲームで、手持ちのカードの役の強さを競い合ってゲームの勝敗を決めるものです。<br>ポーカーは限られた情報からプレイヤーのカードを推測する不完全情報ゲームであり、相手の役と自分の役どちらが強いか読み合う心理戦が醍醐味とされています。<br>世界的に有名なバリエーションの一つは「テキサスホールデム」で、自分の手札とテーブルの共通カードを組み合わせて最強のハンドを作ります。<br>テキサスホールデムは競技人口が1億人以上で、世界中で大会が開かれるほど人気のあるカジノゲームです<br></p>
      <h1>魅力</h1>
      <p>ポーカーの目的は二つあります。<br>一つは最高の役（ハンド）を作り、テーブル上の他のプレイヤー全てを上回ること。<br>もう一つは他のプレイヤー全てを降参させ、ポット（賭け金の総額）を獲得することです。<br>これは、あなたが最高の役を持っていなくても、他のプレイヤーにそれを思わせてしまえば勝つことが可能という、ポーカーの魅力の一つです<br></p>
      <h1>ルールと進行</h1>
     <p>ゲームの進行は配布で各プレイヤーに2枚のカードが配られ、<br>ベットするかしないかを決め、フロップで3枚のカードが公開、ターンで4枚目のカード公開、<br>リバーで5枚目のカードを公開、ショーダウンで残ったプレイヤーが手札を公開し、最強の役を持つプレイヤーが勝者となる、シンプルながらも奥深い戦略が楽しめるゲームです。<p>
    <div class="poker_2">
    <iframe width="400" height="300" src="https://www.youtube.com/embed/axl585df-Ic?si=JJGB9hsYs46gy0sU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Poker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200..900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  

<body>
  <header>
    <h1>Geekpoker</h1>
    <div class="header-list">
    <% if user_signed_in? %>
    <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
    <li><%= link_to "新規登録",new_user_registration_path, class:"post" %></li>
   <li><%= link_to "ログイン", new_user_session_path %></li>
      <li><%= link_to "一覧に戻る", chases_path, class:"show" %></li>

    <% end %>
  </div>
  </header>
  
  <main>
    <%= yield %>
  </main>

  

  <footer>
  </footer>
</body>

</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>

  
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.chases.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<%= link_to "一覧に戻る", chases_path %>
<%= render 'relationships/follow_button', user: @user %>